apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pub.fullname" . }}
  labels:
{{ include "pub.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pub.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pub.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app"]
          args: ["-id", "$(CLIENT_ID)", "-s", "{{ .Values.natsStreamingServerEndpoint }}", "-d", "{{ .Values.delayInBetweenPublish }}", "{{ .Values.subject }}"]   
          env:
          - name: CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
