apiVersion: skaffold/v2beta9
kind: Config
profiles:
- name: pub
  build:
    artifacts:
    - image: 192.168.1.12:32000/gonuts-pub
      context: pub
      kaniko:
        dockerfile: Dockerfile
        cache:
          repo: 192.168.1.12:32000/gonuts-pub
    insecureRegistries:
    - 192.168.1.12:32000
    cluster:
      namespace: gonuts
      dockerConfig:
        secretName: regcred
  deploy:
    helm:
      releases:
      - name: gonuts-pub
        chartPath: k8s-manifest/pub
        artifactOverrides:
          image.repository: 192.168.1.12:32000/gonuts-pub
        namespace: gonuts
        wait: true
- name: sub
  build:
    artifacts:
    - image: 192.168.1.12:32000/gonuts-sub
      context: sub
      kaniko:
        dockerfile: Dockerfile
        cache:
          repo: 192.168.1.12:32000/gonuts-sub
    insecureRegistries:
    - 192.168.1.12:32000
    cluster:
      namespace: gonuts
      dockerConfig:
        secretName: regcred
  deploy:
    helm:
      releases:
      - name: gonuts-sub
        chartPath: k8s-manifest/sub
        artifactOverrides:
          image.repository: 192.168.1.12:32000/gonuts-sub
        namespace: gonuts
        wait: true

- name: stan
  deploy:
    helm:
      releases:
        - name: stan
          chartPath: natss-chart
          namespace: stan
          wait: true
          createNamespace: true
          valuesFiles:
            - natss-chart/values.yaml
      flags:
        upgrade:
          - --install

