apiVersion: skaffold/v1beta15
kind: Config
profiles:
  - name: pub
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.SNAPSHOT}}"
      insecureRegistries: #Use this for local registry.  such as microk8s registry.
      - 192.168.1.12:32000 
      artifacts:
      - image: 192.168.1.12:32000/gonuts-pub
        context: pub
        kaniko:
          dockerfile: Dockerfile
          buildContext:
            localDir: {}
          cache:
            repo: 192.168.1.12:32000/gonuts-pub #for the layers in the Dockerfile
      cluster:
        dockerConfig: 
          secretName: regcred
        namespace: gonuts
    deploy:
      helm:
        releases:
          - name: gonuts-pub
            chartPath: k8s-manifest/pub
            namespace: gonuts
            wait: true
            imageStrategy: 
              helm: {}

  - name: sub
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.SNAPSHOT}}"
      insecureRegistries: #Use this for local registry.  such as microk8s registry.
      - 192.168.1.12:32000 
      artifacts:
      - image: 192.168.1.12:32000/gonuts-sub
        context: sub
        kaniko:
          dockerfile: Dockerfile
          buildContext:
            localDir: {}
          cache:
            repo: 192.168.1.12:32000/gonuts-sub          
      cluster:
        dockerConfig: 
          secretName: regcred
        namespace: gonuts
    deploy:
      helm:
        releases:
          - name: gonuts-sub
            chartPath: k8s-manifest/sub
            namespace: gonuts
            imageStrategy: 
              helm: {}


