apiVersion: v1
kind: Pod
metadata:
  name: kaniko-warmer
  namespace: gonuts
spec:
  containers:
  - name: kaniko-warmer
    image: gcr.io/kaniko-project/warmer:latest
    args: ["--cache-dir=/cache",
           "--image=golang:1.12.10",
           "--image=gcr.io/distroless/base:debug",
           "--image=gcr.io/distroless/base"]
    volumeMounts:
      - name: kaniko-cache
        mountPath: /cache
  restartPolicy: Never
  volumes:
    - name: kaniko-cache
      persistentVolumeClaim:
              claimName: kaniko-cache-claim
