kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kaniko-cache-claim
  namespace: gonuts
spec:
  #storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi