apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "nats-ss.fullname" . }}
  labels:
    app: {{ template "nats-ss.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "nats-ss.name" . }}
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "nats-ss.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "nats-ss.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "nats-ss.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /nats-streaming-server
        args:
          - -m=8222
          - -st=FILE
          - --dir=/nats-datastore
          - --cluster_id=local-stan
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - mountPath: /nats-datastore
          name: nats-datastore
  volumeClaimTemplates:
    - metadata:
        name: nats-datastore
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
#        storageClassName: microk8s-hostpath

