apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sub.fullname" . }}
  labels:
{{ include "sub.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sub.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "sub.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app"]
          args: ["-d", "{{ .Values.delayInBetweenConsumption }}", "-s", "{{ .Values.natsStreamingServerEndpoint }}","--durable","{{ .Values.durableName }}", "--qgroup", "{{ .Values.queueGroup }}", "{{ .Values.subject }}"]   
